CREATE TABLE IF NOT EXISTS Song(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME          VARCHAR,
   RELEASE_DATE  date,
   LYRICS        VARCHAR,
   LENGTH        time,
   ALBUM         VARCHAR,
   ARTIST_ID     INTEGER,
   ARTIST_TYPE   VARCHAR,
   FT_ID         INTEGER,
   FT_TYPE       VARCHAR,
   PATH          VARCHAR
);

CREATE TABLE IF NOT EXISTS Artist(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME          VARCHAR,
   DOB           date
);

CREATE TABLE IF NOT EXISTS Band(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME          VARCHAR
);

CREATE TABLE IF NOT EXISTS Band_Artist(
   BAND_ID       INTEGER,
   ARTIST_ID     INTEGER
);

CREATE TABLE IF NOT EXISTS Album(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   TITLE         VARCHAR,
   SONGS_NO      INTEGER
);

CREATE TABLE IF NOT EXISTS Album_Song(
   SONG_ID       INTEGER,
   ALBUM_ID      INTEGER
);

CREATE TABLE IF NOT EXISTS Playlist(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME          VARCHAR,
   DESCRIPTION   VARCHAR
);

CREATE TABLE IF NOT EXISTS Playlist_Song(
   PLAYLIST_ID   INTEGER,
   SONG_ID       INTEGER
);

CREATE TABLE IF NOT EXISTS Genre(
   ID            INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME          VARCHAR
);

CREATE TABLE IF NOT EXISTS Genre_Song(
   GENRE_ID      INTEGER,
   SONG_ID       INTEGER
);